// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: hello/v1/hello.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "example.com/connrpcothr/rpc/hello/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HeloServiceName is the fully-qualified name of the HeloService service.
	HeloServiceName = "hello.v1.HeloService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HeloServiceGreetProcedure is the fully-qualified name of the HeloService's Greet RPC.
	HeloServiceGreetProcedure = "/hello.v1.HeloService/Greet"
)

// HeloServiceClient is a client for the hello.v1.HeloService service.
type HeloServiceClient interface {
	Greet(context.Context, *connect.Request[v1.Request]) (*connect.Response[v1.Response], error)
}

// NewHeloServiceClient constructs a client for the hello.v1.HeloService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHeloServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HeloServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	heloServiceMethods := v1.File_hello_v1_hello_proto.Services().ByName("HeloService").Methods()
	return &heloServiceClient{
		greet: connect.NewClient[v1.Request, v1.Response](
			httpClient,
			baseURL+HeloServiceGreetProcedure,
			connect.WithSchema(heloServiceMethods.ByName("Greet")),
			connect.WithClientOptions(opts...),
		),
	}
}

// heloServiceClient implements HeloServiceClient.
type heloServiceClient struct {
	greet *connect.Client[v1.Request, v1.Response]
}

// Greet calls hello.v1.HeloService.Greet.
func (c *heloServiceClient) Greet(ctx context.Context, req *connect.Request[v1.Request]) (*connect.Response[v1.Response], error) {
	return c.greet.CallUnary(ctx, req)
}

// HeloServiceHandler is an implementation of the hello.v1.HeloService service.
type HeloServiceHandler interface {
	Greet(context.Context, *connect.Request[v1.Request]) (*connect.Response[v1.Response], error)
}

// NewHeloServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHeloServiceHandler(svc HeloServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	heloServiceMethods := v1.File_hello_v1_hello_proto.Services().ByName("HeloService").Methods()
	heloServiceGreetHandler := connect.NewUnaryHandler(
		HeloServiceGreetProcedure,
		svc.Greet,
		connect.WithSchema(heloServiceMethods.ByName("Greet")),
		connect.WithHandlerOptions(opts...),
	)
	return "/hello.v1.HeloService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HeloServiceGreetProcedure:
			heloServiceGreetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHeloServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHeloServiceHandler struct{}

func (UnimplementedHeloServiceHandler) Greet(context.Context, *connect.Request[v1.Request]) (*connect.Response[v1.Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hello.v1.HeloService.Greet is not implemented"))
}
