apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  containers:
    - name: prometheus
      image: prom/prometheus:v2.47.2
      volumeMounts:
        - name: config
          mountPath: /etc/prometheus
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: prometheus
        items:
          - key: prometheus.yml
            path: prometheus.yml

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
